<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Employment_Consideration</name>
   <tag></tag>
   <elementGuidId>cb3acb7d-4560-4160-adfe-9df6b39428a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-f6522b09-be26-4ebd-9e81-5d710f45fa27 > span.k-select > span.k-icon.k-i-arrow-s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//kendo-dropdownlist[@id='Employment Reciprocity Dropdown']/span/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c9f0f8c-0f16-4e8c-abae-a1554a366302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0fadc74f-6a73-44c8-943f-b1ad8ec5f893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-s</value>
      <webElementGuid>a3f04f87-160a-48b7-afe3-29916635d294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-f6522b09-be26-4ebd-9e81-5d710f45fa27&quot;)/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-s&quot;]</value>
      <webElementGuid>ee1a0cd2-6f47-4d42-bd9f-f64aa170cf62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-f6522b09-be26-4ebd-9e81-5d710f45fa27']/span[2]/span</value>
      <webElementGuid>0176870e-b447-4235-9e27-1fabe7639a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[145]/div[2]/div/kendo-dropdownlist/span/span[2]/span</value>
      <webElementGuid>9b74ff93-b72c-4608-a0b4-0a92f2aa7f0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
