<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_No</name>
   <tag></tag>
   <elementGuidId>5dd56fac-5f8f-4198-8444-869c2784e213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#29f51ab5-8c00-426b-babb-dad6c8ba58e3-No</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>21b01163-7bd6-47d8-b278-58ce4bb48e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cac51d0a-1f6c-4b13-94ff-896e47095e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>1bc8076c-0242-4f58-b4e7-d65615a4f1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>29f51ab5-8c00-426b-babb-dad6c8ba58e3-No</value>
      <webElementGuid>ac8cbad9-79ba-44ee-b9d8-7071515dbc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f297784e-7f0e-4e43-a29f-ad44066b9d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>04e88b5f-9bac-4740-9ca6-02ea37848c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>f24fa855-a985-424d-9764-35d493c627ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;29f51ab5-8c00-426b-babb-dad6c8ba58e3-No&quot;)</value>
      <webElementGuid>197f829d-bbb0-4f56-b181-43df3dd78511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='29f51ab5-8c00-426b-babb-dad6c8ba58e3-No']</value>
      <webElementGuid>ed2c69f3-599d-43d5-9933-287f1d311ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='032c5724-b085-4fde-abaa-924124eaea24']/li</value>
      <webElementGuid>dec408ff-c2cf-4941-8ddc-b0b035a8778d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[75]/following::li[1]</value>
      <webElementGuid>bd0b513e-2912-4cc7-871b-48abbfa146b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add License'])[1]/following::li[1]</value>
      <webElementGuid>95827ef5-42df-4ea8-af37-55a5c5292f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[7]/preceding::li[1]</value>
      <webElementGuid>622b2a96-1d49-41c4-a067-03da6dc79efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::li[2]</value>
      <webElementGuid>5f0e4699-c115-47e8-9dfa-94cc64cb1edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>82c53508-7744-4280-9717-5f15e8b920a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '29f51ab5-8c00-426b-babb-dad6c8ba58e3-No' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>95032ecd-0131-4656-b2da-d719e8c0be0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
