<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clear Button</name>
   <tag></tag>
   <elementGuidId>0ca160cf-0bdd-4b3c-8bfc-98cb2f9a3de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentBody_NYpj3_CWEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_btnClear_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentBody_NYpj3_CWEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_btnClear_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rbDecorated</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentBody$NYpj3_CWEeuCB55hMl16Ow$Dc17_vCgEeuCB55hMl16Ow$Dc17_vCgEeuCB55hMl16Ow$ctl0$ctrlAdvancedFilter2$btnClear</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentBody_NYpj3_CWEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_btnClear_input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Clear</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentBody_NYpj3_CWEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_btnClear_input&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentBody_NYpj3_CWEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_btnClear_input']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ContentBody_NYpj3_CWEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_Dc17_vCgEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_btnClear']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/div/div/span/input</value>
   </webElementXpaths>
</WebElementEntity>
