<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Yes</name>
   <tag></tag>
   <elementGuidId>d4d2c47b-addd-4ccf-a2bc-08377980ca74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#55717f36-1a38-4f4b-bc0a-c02f2474d09c-Yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ce2eb436-cd3f-4bb0-afac-cf97138e3205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d811e35e-3006-46b6-91be-a8d3ed5c918a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>6d785397-f897-478d-8b90-3a7a7e676865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>55717f36-1a38-4f4b-bc0a-c02f2474d09c-Yes</value>
      <webElementGuid>daf9d71a-6af6-4937-922f-43259f926f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>281593d7-03ca-40ae-bb12-dd40a905f770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9c7557f3-7c76-4d71-9df2-39b754d423a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>151fe2b1-ac63-410e-8997-6bbee0fc17f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;55717f36-1a38-4f4b-bc0a-c02f2474d09c-Yes&quot;)</value>
      <webElementGuid>8395e504-c093-4cf4-a342-4b17da1cd44e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='55717f36-1a38-4f4b-bc0a-c02f2474d09c-Yes']</value>
      <webElementGuid>2eeb37e6-86a3-41fe-959a-601977488d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='b7c9364d-4ee1-4bf0-876f-7ec540f45df7']/li[3]</value>
      <webElementGuid>27f7a037-2258-463e-9ca3-4c930e721521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/following::li[1]</value>
      <webElementGuid>9c39294e-b17d-4f23-a500-72f9c7977964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[78]/following::li[2]</value>
      <webElementGuid>ff952d2d-a60f-4775-8438-183caeedef79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[1]</value>
      <webElementGuid>42aa1381-8ac4-488f-a3b2-a0207688ab57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::li[1]</value>
      <webElementGuid>a4b9e8f3-71ff-4d47-9b09-560497b67ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>8358c2d8-db8b-4678-9f39-d3acbd6cbe99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '55717f36-1a38-4f4b-bc0a-c02f2474d09c-Yes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>3d1b840b-69c8-45db-baa4-ae689edd37e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
