<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Fail</name>
   <tag></tag>
   <elementGuidId>60bec8ff-1e45-40a2-b9ac-4c059d4bec11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Fail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b1324079-0115-4553-8ffc-d8d999655886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>909f4669-37eb-4308-9c35-2395c955070c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-selected ng-star-inserted</value>
      <webElementGuid>2000661e-72e7-46e0-ac6b-81678c0ee468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Fail</value>
      <webElementGuid>8f418173-4afa-44ef-8639-b06b6237de75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>959cbe3b-b5ae-495e-bddd-4a6e431d303b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>43a5dddd-6d1a-438c-8769-f17baeb339ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fail</value>
      <webElementGuid>a6b92be6-1ff1-40a0-9b5f-2ebf07b6648c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Fail&quot;)</value>
      <webElementGuid>22eca4fb-844b-4dee-86ee-3dda2b9b8b04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Fail']</value>
      <webElementGuid>2b5a0db4-da8b-4aeb-a815-742310a635c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='1bf5871f-c93f-47b4-b2d4-0b4899f7db46']/li[2]</value>
      <webElementGuid>ed15c54e-54e2-447d-8b58-e98640d4d062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pass'])[1]/following::li[1]</value>
      <webElementGuid>30a3d38e-17d2-4d51-8b6f-f43ab182af32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[5]/following::li[2]</value>
      <webElementGuid>fd213b54-f6b1-49ea-9bb8-e2982fef5ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Show'])[1]/preceding::li[1]</value>
      <webElementGuid>87eddcfc-8e7e-4649-b0ae-73dffbde809d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waived'])[1]/preceding::li[2]</value>
      <webElementGuid>cf18cea9-9526-4440-813a-54e13b8ba837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>92f1f0a3-9c35-47ec-8c94-dfb50d4b4b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Fail' and (text() = 'Fail' or . = 'Fail')]</value>
      <webElementGuid>fc7fc929-45e1-44cc-9747-d3e6fa0ffbd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
