<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pending</name>
   <tag></tag>
   <elementGuidId>aba79dac-d316-45fb-bf2f-50c8856665a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pending</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>60c74be3-d89f-47d3-8b51-f0db57abc530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fc506082-a37b-4cba-b9a4-6aac2b630fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-selected ng-star-inserted</value>
      <webElementGuid>efbf7dc1-0f50-4354-87bc-0655c2c93b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pending</value>
      <webElementGuid>8883cf69-77a1-4d88-931d-e3ba9dc6d5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fcabba0b-2000-4486-92e8-887ba84cb52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>af8b7139-1e22-43ba-821e-cf1ef298ea41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending</value>
      <webElementGuid>c839f3ab-620e-4603-97bc-acd8b0f2eebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pending&quot;)</value>
      <webElementGuid>2e453923-7c92-4dca-9edc-87770e75d4f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pending']</value>
      <webElementGuid>ae041566-1cae-4211-8d92-00aea81526ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='1bf5871f-c93f-47b4-b2d4-0b4899f7db46']/li[5]</value>
      <webElementGuid>70cafc02-23fb-403e-a184-de308bd7ed33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waived'])[1]/following::li[1]</value>
      <webElementGuid>aa27f7c4-3918-4bef-91e8-25e62bf27896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Show'])[1]/following::li[2]</value>
      <webElementGuid>73e7711b-4c5b-4e43-9a5a-27261226cb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::li[1]</value>
      <webElementGuid>7da54143-4ab1-4d6f-924c-f4dce1b26f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::li[1]</value>
      <webElementGuid>e117ba77-42e4-4239-bd9b-3d69e7f45608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[5]</value>
      <webElementGuid>8bdfaf61-0726-4106-919a-b22a89ff89d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pending' and (text() = 'Pending' or . = 'Pending')]</value>
      <webElementGuid>8d8bee2f-f35c-41a2-9db7-336cf05669ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
