<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pass</name>
   <tag></tag>
   <elementGuidId>7641191f-919d-4c26-a297-06b96505f861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pass</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5d21e029-6e35-4fd2-8068-8af9a1fb6d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3da36f9c-e14e-4c4a-99f0-abea7b340910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-selected ng-star-inserted</value>
      <webElementGuid>fd8c1988-9ff6-4245-9384-f3aca7829277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pass</value>
      <webElementGuid>86f38b6c-4d12-490d-89be-9b2465e4c1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>617668ec-8fdf-47ae-9537-ae12f6502511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec2a6b46-cf1e-4d55-904a-aeddac2c4f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pass</value>
      <webElementGuid>6a398210-9867-49b6-9a66-3350945746bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pass&quot;)</value>
      <webElementGuid>a677b70d-24a0-4b50-9e23-bba4517f75ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pass']</value>
      <webElementGuid>5375b067-598b-4d09-aac2-88b1681b2e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='1bf5871f-c93f-47b4-b2d4-0b4899f7db46']/li</value>
      <webElementGuid>b39a3f57-1d68-4b95-8341-6666c0478241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[5]/following::li[1]</value>
      <webElementGuid>35db1ef7-7f93-42a1-b999-353bdc2ce98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font Family'])[3]/following::li[1]</value>
      <webElementGuid>8da19b31-a4d9-4fd2-aff3-408fa1cb3ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fail'])[1]/preceding::li[1]</value>
      <webElementGuid>f09973aa-76f9-4741-adc9-6e7c58495ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Show'])[1]/preceding::li[2]</value>
      <webElementGuid>9a96b0a2-c022-47dd-9a2e-a42ea82d87e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>77e39193-aad8-47a7-96d9-5a152b9a3012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Pass' and (text() = 'Pass' or . = 'Pass')]</value>
      <webElementGuid>379ee737-1ac8-41f5-926e-9e2d2716127b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
