<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Waived</name>
   <tag></tag>
   <elementGuidId>8e372366-7571-4212-aff2-95306a671989</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Waived</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>bf8b697c-a188-4565-b092-d3b966a6ba39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c1aeaf2c-4b5d-4358-aa94-e790ad63b542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-selected ng-star-inserted</value>
      <webElementGuid>0b166e82-195e-4ff4-9f6e-6291b21fa16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Waived</value>
      <webElementGuid>1cf18d9d-59d6-4611-858c-893d85da91f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b3de7968-0de0-459f-908f-3f3ca1c9ee23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>08917aaf-3d3e-463f-9805-f3722986b454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Waived</value>
      <webElementGuid>646791ec-3523-4708-a56c-c09e1ce54857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Waived&quot;)</value>
      <webElementGuid>d6e96c11-3c23-4b09-b1fd-87e9946f4084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Waived']</value>
      <webElementGuid>f0c12629-7d7f-4e2b-881b-8dbae686ad89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='1bf5871f-c93f-47b4-b2d4-0b4899f7db46']/li[4]</value>
      <webElementGuid>38f81cca-38e6-4f6b-8438-5166371a88ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Show'])[1]/following::li[1]</value>
      <webElementGuid>17342799-629f-4623-8c72-209a479190c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fail'])[1]/following::li[2]</value>
      <webElementGuid>acc2ca89-0858-440c-a8b8-1fb5c5dbf26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/preceding::li[1]</value>
      <webElementGuid>fc3f1d86-4863-4260-9ac7-e4c642c1cbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::li[2]</value>
      <webElementGuid>9e406e32-babd-468b-81a8-4be8638e29d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]</value>
      <webElementGuid>76059f5f-8721-4d94-9912-082b0bd58813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '6d0d5e2a-239f-42b5-9fa7-f89cde14149f-Waived' and (text() = 'Waived' or . = 'Waived')]</value>
      <webElementGuid>110209b1-4bd2-4d76-a1c0-c0b9db2fbf72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
