<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_modalDialogBodyValidationDetails</name>
   <tag></tag>
   <elementGuidId>f01815f5-a7db-45be-bdf4-9ceca36820c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#validationbuttonArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='validationbuttonArea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>936c3870-f679-4a30-82ab-792cffae0d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationbuttonArea</value>
      <webElementGuid>3a5ab1f6-ee22-4b10-89ac-82b884d5f088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Out of State License: Please make a selection from the Out of State License dropdown.Denied Renewal: Please make a selection from the Denied Renewal dropdown.Discipline Since Licensed: Please make a selection from the Discipline Since Licensed dropdown.</value>
      <webElementGuid>18c2d250-2e16-422b-891b-6defd3e3a390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validationbuttonArea&quot;)</value>
      <webElementGuid>a668fce0-2f31-41a2-aea5-3a4767f4c773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='validationbuttonArea']</value>
      <webElementGuid>213722a4-c248-44ad-ab27-d7a2646ab7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='validationErrorModal']/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>063d1612-78e1-44de-a910-3b55f3647edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Validation Errors Found'])[1]/following::div[4]</value>
      <webElementGuid>3b01863e-04b2-407b-bb6b-15dbc0773af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'validationbuttonArea', '&quot;', ')')])[1]/following::div[9]</value>
      <webElementGuid>b903f588-970a-4247-bfa1-920089c277bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>66374eff-f1a7-46ea-bf5f-56d58f5f94f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'validationbuttonArea' and (text() = 'Out of State License: Please make a selection from the Out of State License dropdown.Denied Renewal: Please make a selection from the Denied Renewal dropdown.Discipline Since Licensed: Please make a selection from the Discipline Since Licensed dropdown.' or . = 'Out of State License: Please make a selection from the Out of State License dropdown.Denied Renewal: Please make a selection from the Denied Renewal dropdown.Discipline Since Licensed: Please make a selection from the Discipline Since Licensed dropdown.')]</value>
      <webElementGuid>98af0641-56c2-4d10-b9ab-f7eb2a7251ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
