<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Cosmetologist</name>
   <tag></tag>
   <elementGuidId>e94c8ea9-8006-4a5f-a896-4405798926c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Cosmetologist']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#60dcbc41-03bc-4998-89ec-79ad73ba6b34-Cosmetologist</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>29e54918-5871-4b02-8df9-0bbcde606297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f392d636-bed7-40bf-bd64-10bb3f38990b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>bb4afda7-a58b-4e81-9a64-508f8176b5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>60dcbc41-03bc-4998-89ec-79ad73ba6b34-Cosmetologist</value>
      <webElementGuid>9a2e90d5-2564-489c-808a-e2ba354e53a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4a886935-d4ec-41f7-b72f-ea1e48cd63b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>176b163d-e9b5-452d-833d-fc5c1da1b0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cosmetologist</value>
      <webElementGuid>a7be1738-bffb-48f8-8686-76fafa1b8406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;60dcbc41-03bc-4998-89ec-79ad73ba6b34-Cosmetologist&quot;)</value>
      <webElementGuid>e125642c-ba6c-4ada-bac4-f999b42fb38c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='60dcbc41-03bc-4998-89ec-79ad73ba6b34-Cosmetologist']</value>
      <webElementGuid>64bdbf20-39c9-4cac-b20a-eae9c101280c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='90b3a5b6-837f-456d-9951-46c60ea3af74']/li</value>
      <webElementGuid>b07e18c4-44b8-49e2-8607-65a6c654724e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[8]/following::li[1]</value>
      <webElementGuid>fa732d24-80ca-463a-add7-5f99bc430d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Application Checkboxes:'])[1]/following::li[1]</value>
      <webElementGuid>dc37d2dd-6ce0-4f12-bcf3-1117847c4846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[1]</value>
      <webElementGuid>f2e9f152-a991-4b1d-9c0b-f16050fb4274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::li[1]</value>
      <webElementGuid>344a0707-1276-48b6-8c44-c2585ef02753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cosmetologist']/parent::*</value>
      <webElementGuid>827bf6c0-dac9-4cff-94d4-2e4262e8fff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>5cff1971-09db-4ab5-a8a8-aba8028ab323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '60dcbc41-03bc-4998-89ec-79ad73ba6b34-Cosmetologist' and (text() = 'Cosmetologist' or . = 'Cosmetologist')]</value>
      <webElementGuid>1158e387-94bc-4c79-a268-fd6cabec4594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
