<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select License Drop-down</name>
   <tag></tag>
   <elementGuidId>922c983c-0555-4e75-8554-677527398d59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[13]/div[2]/div/kendo-dropdownlist/span/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-be93c9a6-f347-4a52-a7c1-25201c2cdb24 > span.k-select > span.k-icon.k-i-arrow-s</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;k-be93c9a6-f347-4a52-a7c1-25201c2cdb24&quot;)/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-s&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10a78965-f89c-408b-b593-9d9c9011d446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>29825351-86e7-4a45-8d8d-f8f4c0f87780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-s</value>
      <webElementGuid>dcbab3b8-736e-4fd3-bc6f-f2546a7d5ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-be93c9a6-f347-4a52-a7c1-25201c2cdb24&quot;)/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-s&quot;]</value>
      <webElementGuid>d803d143-6613-4b8c-8c08-0a6f188d72fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-be93c9a6-f347-4a52-a7c1-25201c2cdb24']/span[2]/span</value>
      <webElementGuid>e340f259-4a45-4d98-9ea0-1669d4589292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/kendo-dropdownlist/span/span[2]/span</value>
      <webElementGuid>bb3f717a-a3f5-457f-b6b7-1b5354e93c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
