<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exam_Type_Arrow</name>
   <tag></tag>
   <elementGuidId>66b48471-084f-4a5e-8a47-ae7b52c454d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//kendo-dropdownlist[@id='Exam Type']/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-icon.k-i-arrow-s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e16c955d-79d0-42c0-a7c6-5d5a3793e888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e78c7d5a-be78-4f31-b195-bb1c4dd88390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-s</value>
      <webElementGuid>78e6a540-0656-4917-9627-1c257bf59782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-8d9ace97-35fe-4d0c-9636-86b1c4ffba11&quot;)/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-s&quot;]</value>
      <webElementGuid>a13931ba-4d8b-4c82-98a5-b6dcd0e50850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-8d9ace97-35fe-4d0c-9636-86b1c4ffba11']/span[2]/span</value>
      <webElementGuid>76504585-8416-4486-b394-4c9615b5f03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>17b304fa-8e8c-47f0-931a-431ecc55339d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
