<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Jurisprudence</name>
   <tag></tag>
   <elementGuidId>2b88604a-34a2-410d-a7a8-2b25cac86d6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#103f1ce9-92a5-4543-80cd-8a26251a0577-Jurisprudence</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>de03a68d-e03a-4d9a-8d29-75d04087d05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>61c40d54-daa2-4fc1-8c54-a5ba26c226c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-selected ng-star-inserted</value>
      <webElementGuid>aebe0996-e236-4b96-9316-507350d4c748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>103f1ce9-92a5-4543-80cd-8a26251a0577-Jurisprudence</value>
      <webElementGuid>8b87a157-b58a-4a63-861b-8a05dd8fe9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4448bc58-c40c-49bb-840d-83f17338fde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cc0c5804-3378-45f4-b916-9bdbfaeb7a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jurisprudence</value>
      <webElementGuid>b86554ad-e79a-401a-a68f-244e34f49823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;103f1ce9-92a5-4543-80cd-8a26251a0577-Jurisprudence&quot;)</value>
      <webElementGuid>03369f9a-4b49-4853-b692-b49b2a42d43a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='103f1ce9-92a5-4543-80cd-8a26251a0577-Jurisprudence']</value>
      <webElementGuid>169b6395-fd74-4310-b895-de685c100831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='a147248f-c970-4a21-bbbb-31e5e6126f59']/li</value>
      <webElementGuid>af396ce3-5fe0-4299-8fe3-c0cb0c2f0c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[7]/following::li[1]</value>
      <webElementGuid>c1f984a7-29af-4724-acbd-91b29a95cfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font Family'])[3]/following::li[1]</value>
      <webElementGuid>ae6accbf-b054-415a-aab4-3e59da6f9e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPTE'])[1]/preceding::li[1]</value>
      <webElementGuid>8d4b20bf-39fe-4db7-a9fd-72ee7770b898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[2]</value>
      <webElementGuid>6849e7bc-c6a1-4ddf-abd8-c6ab93394d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>44a83362-8413-4e97-81bc-6a0af306a441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '103f1ce9-92a5-4543-80cd-8a26251a0577-Jurisprudence' and (text() = 'Jurisprudence' or . = 'Jurisprudence')]</value>
      <webElementGuid>0f94ad1e-f2bf-4bc3-a729-ede4b01585e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
