<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add New Row</name>
   <tag></tag>
   <elementGuidId>5e6042ce-47c5-4220-b39d-1cc733669a3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RRC_ConvictionInformation > kendo-grid.rrc-grid.k-widget.k-grid > kendo-grid-toolbar.k-grid-toolbar.k-header.ng-star-inserted > button.k-button.k-grid-add-command.k-button-icontext.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RRC_ConvictionInformation']/kendo-grid/kendo-grid-toolbar/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aa989325-8e40-4b1c-9b36-cf76c879b59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>plus</value>
      <webElementGuid>761ec017-2330-4c20-9cba-3ce854ab94b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-grid-add-command k-button-icontext ng-star-inserted</value>
      <webElementGuid>4d5fcbbc-3783-4cbc-be2a-705e3ef50731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0bdd324d-9b07-47a0-b0dc-4b8b1daf6b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17c89f1a-cbdc-483c-a383-3546820daa75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>22c51e13-271c-40dd-aa2d-ff0ba8a38efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Row</value>
      <webElementGuid>3aab00b9-5399-4ffc-989f-c0710b38d4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RRC_ConvictionInformation&quot;)/kendo-grid[@class=&quot;rrc-grid k-widget k-grid&quot;]/kendo-grid-toolbar[@class=&quot;k-grid-toolbar k-header ng-star-inserted&quot;]/button[@class=&quot;k-button k-grid-add-command k-button-icontext ng-star-inserted&quot;]</value>
      <webElementGuid>22dded8a-406e-47c6-a1fa-6fe4be08b85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8755ed7-781c-4626-9078-5159a33b0bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>plus</value>
      <webElementGuid>766645f0-db69-47b1-9637-db0a43f84c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-grid-add-command k-button-icontext ng-star-inserted</value>
      <webElementGuid>b2d9ae63-2a73-4958-b880-5b8c0a31d736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0cc2db4-22d1-423d-a807-6b8440da3bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28d80324-3d03-4c2f-a7bd-e70e1094650e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>abc95528-9fb8-4b13-919e-86a137db9ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Row</value>
      <webElementGuid>67976f84-f293-4e3b-b8f0-f42fa1431178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RRC_ConvictionInformation&quot;)/kendo-grid[@class=&quot;rrc-grid k-widget k-grid&quot;]/kendo-grid-toolbar[@class=&quot;k-grid-toolbar k-header ng-star-inserted&quot;]/button[@class=&quot;k-button k-grid-add-command k-button-icontext ng-star-inserted&quot;]</value>
      <webElementGuid>c93c8d5c-f849-4cd0-a6be-108133d05ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RRC_ConvictionInformation']/kendo-grid/kendo-grid-toolbar/button</value>
      <webElementGuid>6d0fd287-d200-455b-8655-61abb8c660c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drug or Alcohol Related Convictions.'])[1]/following::button[1]</value>
      <webElementGuid>461738c3-9592-4c87-9aa8-c946614d8095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[6]/preceding::button[1]</value>
      <webElementGuid>41ac9017-b731-4465-bc7b-57f78068e7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records available.'])[11]/preceding::button[2]</value>
      <webElementGuid>83de4e4b-ea84-4eb1-a41a-71a8e9c9f2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[208]/div[2]/div/kendo-grid/kendo-grid-toolbar/button</value>
      <webElementGuid>91b2fbff-e2a1-479b-a06e-75a4d8d1f47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add New Row' or . = 'Add New Row')]</value>
      <webElementGuid>e0c4e038-a278-4b63-9f68-9d4231c0911c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
