<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_upload_btnUploadButtonProbationDocuments2</name>
   <tag></tag>
   <elementGuidId>46a7cd4e-6f8c-4e44-87ec-bb2213a40729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUploadButtonProbationDocuments2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnUploadButtonProbationDocuments2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b3125f7-a2d0-4c9a-8f00-8c928e6b0c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4603bedb-2bf4-4b38-9c44-403c35d06313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>adeee1c7-b08e-4450-bb2a-d0464242c466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>btnUploadButtonProbationDocuments2</value>
      <webElementGuid>017cf493-18bf-4597-8484-47396c3eee2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>14d6f751-b59e-4e28-94c4-bf2305941b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Upload Documents</value>
      <webElementGuid>8c5d0f79-6c6f-465f-82e1-ec6e19354651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUploadButtonProbationDocuments2</value>
      <webElementGuid>b7a3805d-90a3-4f85-a3cf-a3fc2011be78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldtype</name>
      <type>Main</type>
      <value>uploadbutton</value>
      <webElementGuid>69deabf9-69c5-420e-b652-943e8eeea38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldname</name>
      <type>Main</type>
      <value>btnUploadButtonProbationDocuments2</value>
      <webElementGuid>38d778d4-a9a5-4bb6-b52d-baef00456283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldvalueid</name>
      <type>Main</type>
      <value>1a44bdfd-fb2e-d81c-2753-cb24ea06c124</value>
      <webElementGuid>1fab957e-e82b-44d6-a6a0-6b61ba648a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-button ng-star-inserted</value>
      <webElementGuid>c4aec723-f258-465f-bb99-51128599c9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUploadButtonProbationDocuments2&quot;)</value>
      <webElementGuid>5c924ce4-1543-40e2-bdf3-3ec74e1c38d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnUploadButtonProbationDocuments2']</value>
      <webElementGuid>29cfbefc-036b-430e-8916-defa48f0289d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/viewer-tab-form/div/div[2]/div/div/div[210]/div[2]/input</value>
      <webElementGuid>cbba4e5a-0685-455b-9aac-5a91b292e6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[210]/div[2]/input</value>
      <webElementGuid>318bd4c9-9e62-4b0c-925d-358eabcd54b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'btnUploadButtonProbationDocuments2' and @id = 'btnUploadButtonProbationDocuments2']</value>
      <webElementGuid>0908944d-f6f6-4d4a-8e8b-9032cbb96ea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
