<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Final_Outcome</name>
   <tag></tag>
   <elementGuidId>8a7f4187-712a-4ebc-a3ca-3ca668112731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Col_d2593b98d7eb77f95c0155594a524efa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Col_d2593b98d7eb77f95c0155594a524efa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64a91bf6-fa03-4d1e-9ac8-5f48d62017e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Final Outcome</value>
      <webElementGuid>33e17bd8-73d0-45df-b11d-9d1a561271d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Col_d2593b98d7eb77f95c0155594a524efa</value>
      <webElementGuid>13bcf5ec-4938-4e59-9668-f6237eda2afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef183934-6fc8-422d-9443-6ae003cec8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>36dfdc4f-0dc2-4406-a2ca-50bad3d31c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RRC_ConvictionInformation&quot;)/kendo-grid[@class=&quot;rrc-grid k-widget k-grid&quot;]/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;k-grid-add-row k-grid-edit-row ng-star-inserted&quot;]/td[@class=&quot;72efb828-a16b-cc68-f89c-e3ba850bebf4 hAlignLeft vAlignMiddle ng-star-inserted&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>44a1d6a5-6d1b-409a-86b2-2a93fdaa5fbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Col_d2593b98d7eb77f95c0155594a524efa']</value>
      <webElementGuid>95c8de59-9713-4baf-944c-d9d6210952c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RRC_ConvictionInformation']/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td[5]/input</value>
      <webElementGuid>bcb99415-e6cd-4b01-ab04-45beca900a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>abdfead5-2b39-4bbb-bb50-a033e39b1db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Final Outcome' and @name = 'Col_d2593b98d7eb77f95c0155594a524efa' and @type = 'text']</value>
      <webElementGuid>efc264a9-0f80-4360-871e-794a744ceeac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
