<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_of_Offense</name>
   <tag></tag>
   <elementGuidId>1a981d93-bcf0-4d1c-b254-3c99a7a5b156</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Col_d521e471258063f7d736e12155ed8845&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Col_d521e471258063f7d736e12155ed8845']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de4b0206-d2e4-4656-b8e8-a21fb4dcd9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Description of Offense</value>
      <webElementGuid>b62dd770-adc6-456c-a79d-6b1af47e9da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Col_d521e471258063f7d736e12155ed8845</value>
      <webElementGuid>e8bccb6b-85f9-4b8c-8df9-8efa4738a655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>530524b5-2509-4f25-a487-c0eb7a906ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>26b44801-7f93-4a3c-90f7-6c2d033de6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RRC_ConvictionInformation&quot;)/kendo-grid[@class=&quot;rrc-grid k-widget k-grid&quot;]/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;k-grid-add-row k-grid-edit-row ng-star-inserted&quot;]/td[@class=&quot;e3a03199-85d2-6966-8498-aa01bf036cd4 hAlignLeft vAlignMiddle ng-star-inserted&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>6a4b260e-df5d-467c-8d1e-03171f1265ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Col_d521e471258063f7d736e12155ed8845']</value>
      <webElementGuid>00ce00bb-c002-4155-b32a-62609292ebfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RRC_ConvictionInformation']/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>adf01521-4abe-453a-bc9b-67fd04eef4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>633c4b01-1c2d-455f-8818-9d79ce014844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Description of Offense' and @name = 'Col_d521e471258063f7d736e12155ed8845' and @type = 'text']</value>
      <webElementGuid>d4167bc3-71d8-4f10-a5b5-d55e8392d383</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
