<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DoC</name>
   <tag></tag>
   <elementGuidId>ce1498e4-d5cc-4ca8-a2a6-6ca565168d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//kendo-dateinput/span/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Date of Conviction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-ada986a9-fe16-47a2-a32e-cfeb85b83bc2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07291eed-49a5-4ae2-bc98-9fd920e567a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1acea16c-6b54-4219-8f7c-849437c378cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5aeff5df-ed5a-4f64-a632-9961811b7cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ee865852-33fb-4d9b-b262-8c2068aa5bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5e9128e7-3fcc-492c-a0a3-26a2c4506010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>064bedbb-760b-4adb-9cdd-5e3f9869c0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-ada986a9-fe16-47a2-a32e-cfeb85b83bc2</value>
      <webElementGuid>83434029-0447-4bf1-a677-9ec8a7060bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Date of Conviction</value>
      <webElementGuid>e3621379-0f93-4670-b1d8-ec7957eb49e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>66d23927-4717-4246-9631-db01f3001ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>bc5caf67-9d35-4a0b-b6c5-d0c0852f084c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dfb5de1b-a656-4eec-8533-cc0501e01db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9d2d5b8-c015-4b3c-82ce-2c83d393db06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ddd632e-9eed-4ed3-b871-ad75456e5b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-ada986a9-fe16-47a2-a32e-cfeb85b83bc2&quot;)</value>
      <webElementGuid>c11e22b2-4be5-4971-85a1-764df1b25f3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-ada986a9-fe16-47a2-a32e-cfeb85b83bc2']</value>
      <webElementGuid>730bfc41-d3ed-4829-9ef1-bf36a2b57c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RRC_ConvictionInformation']/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td[4]/kendo-datepicker/span/kendo-dateinput/span/input</value>
      <webElementGuid>b1e8176a-740a-46df-a87a-0c4c835a75ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-dateinput/span/input</value>
      <webElementGuid>033bae8e-db2d-45d0-8066-5987e1833ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-ada986a9-fe16-47a2-a32e-cfeb85b83bc2' and @title = 'Date of Conviction']</value>
      <webElementGuid>0a65c42c-d923-4b5b-af3f-ae6924ef0341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
