<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Nebraska</name>
   <tag></tag>
   <elementGuidId>a15be94f-6012-4378-bb92-9c940a1dce00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Nebraska']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f91a7091-c359-4cca-beda-fee827abac17-NE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f011e8c1-399a-474f-b4e1-0492cf130a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8d892794-44d2-4e12-ba99-b0864c73965b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>7fefda43-5985-49cb-a9d0-5d349fe6f104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f91a7091-c359-4cca-beda-fee827abac17-NE</value>
      <webElementGuid>6de5c1f1-8700-4af3-9b12-b2e90a59945d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d960d1e1-fc2e-41cd-857a-c0fee0423e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a32f1dfb-21d9-42f0-a9fe-4bee432127b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nebraska</value>
      <webElementGuid>c7be5198-045c-441b-b6d2-d41ab6b45f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f91a7091-c359-4cca-beda-fee827abac17-NE&quot;)</value>
      <webElementGuid>5364d41e-48fd-4be6-b245-d776eff248d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='f91a7091-c359-4cca-beda-fee827abac17-NE']</value>
      <webElementGuid>b3ecf554-20f4-40b8-8a7f-f1ec7707513f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='1d975185-91be-4c39-a6cf-9ad62c76ab10']/li</value>
      <webElementGuid>823d8a3a-2108-4145-885e-9a6802ce4ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[72]/following::li[1]</value>
      <webElementGuid>4754711d-e80c-47bb-b99b-a71efca4be80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add License'])[1]/following::li[1]</value>
      <webElementGuid>2188d6b0-e906-4069-a526-e19d7b8b56b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alabama'])[1]/preceding::li[1]</value>
      <webElementGuid>76bf24d4-9eec-44d8-a05c-2e6403cb7226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alaska'])[1]/preceding::li[2]</value>
      <webElementGuid>19807284-0f68-4ff1-b636-0e1e756d42cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nebraska']/parent::*</value>
      <webElementGuid>420928ab-e428-459b-8337-cb0c9c2b220c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>fba5cc12-0615-4ed1-991c-97a1677777c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'f91a7091-c359-4cca-beda-fee827abac17-NE' and (text() = 'Nebraska' or . = 'Nebraska')]</value>
      <webElementGuid>85b5ddf2-236c-45b6-b2ed-73244e53f834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
