<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Jurisdiction-arrow</name>
   <tag></tag>
   <elementGuidId>db887f95-d804-42e0-8030-68027e45291e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//kendo-dropdownlist[@id='Jurisdiction State']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-772a3e89-0c07-48f8-92d9-3defa131f34d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6849d82c-ffc2-465e-aa3a-47ceec05a520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>14cfc4ca-2d83-4e6d-a336-9e0ebbba59e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>debdf9ee-a256-41df-b555-e97849dc1b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>5025a1d4-3a8e-40cb-9d8d-e68c29e05788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>2825746a-807e-4cae-97c9-3db3fb2503fb</value>
      <webElementGuid>53203841-1168-4385-8163-99e8fc019faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-772a3e89-0c07-48f8-92d9-3defa131f34d</value>
      <webElementGuid>a00ad925-2569-4458-a0f9-4569bc453d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>6a78f62a-6cf3-4035-a0c6-0ba08cc8a98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>197f7702-adc7-4c70-9741-47f5a4107675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>169128a1-a6bb-44c4-9e64-e17248906c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91e8aa32-f3e7-4a3b-9cf1-6ac49de7f72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8515d0ef-4047-4c36-a536-55e8fc792f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3c936ac0-9ce7-4afe-adbd-13492fcc2fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>f91a7091-c359-4cca-beda-fee827abac17-Select Item</value>
      <webElementGuid>993745aa-7f61-4206-81dc-c1fa1062d3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-dropdown-wrap k-state-default</value>
      <webElementGuid>ba044478-e5f7-4efe-b538-1e59f4066bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Item</value>
      <webElementGuid>6bbea397-54c1-4b2a-85c8-4aaffbe157b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-772a3e89-0c07-48f8-92d9-3defa131f34d&quot;)</value>
      <webElementGuid>fa38bcb9-7762-4845-bd97-0d475bc635f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='k-772a3e89-0c07-48f8-92d9-3defa131f34d']</value>
      <webElementGuid>33426e07-b83d-48ee-bfe3-3abced71e64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-dropdownlist[@id='Jurisdiction State']/span</value>
      <webElementGuid>ac83af3c-fc6a-42bc-9680-0ecba719ba70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final Outcome'])[1]/following::span[5]</value>
      <webElementGuid>23d26116-8aaa-47c5-ae1a-f1f333325304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Conviction'])[1]/following::span[8]</value>
      <webElementGuid>eab4b591-d508-45cd-9a6d-da86f2e926ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records available.'])[11]/preceding::span[8]</value>
      <webElementGuid>046db45c-72ce-4645-8db8-4b1d941f04a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/kendo-dropdownlist/span</value>
      <webElementGuid>970c134d-faf5-46c0-b84e-6a933e32d371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'k-772a3e89-0c07-48f8-92d9-3defa131f34d' and (text() = 'Select Item' or . = 'Select Item')]</value>
      <webElementGuid>19b4e1cb-5f2f-4d57-af3c-736a94a5511e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
