<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_No</name>
   <tag></tag>
   <elementGuidId>51b47b2a-fd65-4dc3-b018-8bd3142a1bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f02f6b80-cf00-4e48-b884-1a5c2274b518-No</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>26cb2880-1d7f-46ce-b8cf-9f2d835040b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>efbfd1be-5cb0-4380-96e3-26d42185b013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>83be3ecf-e236-4cda-827d-aa6aeeec493f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f02f6b80-cf00-4e48-b884-1a5c2274b518-No</value>
      <webElementGuid>400f4a17-da05-4c0b-9895-5c13a01f0cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>da0c6af0-cd1d-4249-8b80-c0a288a70c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>04150cbc-1bb2-4e17-99e2-7857f5d3cc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>0a83e0fb-7564-4abd-9f88-eb208d5cf047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f02f6b80-cf00-4e48-b884-1a5c2274b518-No&quot;)</value>
      <webElementGuid>ad609afe-1a92-4960-84c1-3004d2836c54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='f02f6b80-cf00-4e48-b884-1a5c2274b518-No']</value>
      <webElementGuid>e75a3700-569f-4596-8dc1-48682c635d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='1e7fd010-ce42-4ecb-a86c-652430dbbaee']/li[2]</value>
      <webElementGuid>688b4150-5921-4aa8-b1d4-e6490fe0d8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[72]/following::li[1]</value>
      <webElementGuid>893861cf-17d1-4a0a-a25d-395892d9d847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add License'])[1]/following::li[2]</value>
      <webElementGuid>4d8a11c3-510e-412c-8b7a-fc8f48f529a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[6]/preceding::li[1]</value>
      <webElementGuid>7782ff9d-ba5d-4e0f-b73a-0c63451c31a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[2]</value>
      <webElementGuid>6e428bc4-461a-4406-836b-8b2470f211c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>3f740200-d0ba-4f99-9124-358d66d2f398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'f02f6b80-cf00-4e48-b884-1a5c2274b518-No' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>74a080a6-1a4f-416a-8cb6-9ff5143fe5a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
