<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Yes</name>
   <tag></tag>
   <elementGuidId>69551c36-e430-4182-9d08-cc6cf8ccbb25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f02f6b80-cf00-4e48-b884-1a5c2274b518-Yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fdd0dc2e-c75e-4795-85f4-c541a4d6bcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ee47b70b-e9d7-4af9-ada8-4610a990356c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>cf87c4ca-af7b-427e-a45e-357d476e9628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f02f6b80-cf00-4e48-b884-1a5c2274b518-Yes</value>
      <webElementGuid>e369d4df-07c9-4e7d-ae8d-341ba39c16d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b6b9e330-e15c-4d09-b5bd-2375b4726de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7f7b03fd-c8ba-4299-99f4-2e2f7a49dd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>0e6fb2d6-274d-4928-b932-aa638afe298f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f02f6b80-cf00-4e48-b884-1a5c2274b518-Yes&quot;)</value>
      <webElementGuid>e0dde47d-8a8f-473e-95ae-f7b5c6f3fd01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='f02f6b80-cf00-4e48-b884-1a5c2274b518-Yes']</value>
      <webElementGuid>edb095ae-6e47-4a3f-b693-ee77e2f2a576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='1e7fd010-ce42-4ecb-a86c-652430dbbaee']/li[3]</value>
      <webElementGuid>11aecda4-eb25-43b5-ab42-1e037ec68693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[8]/following::li[1]</value>
      <webElementGuid>3e601ac8-7a1e-473d-a1ca-a938e25fe2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[72]/following::li[2]</value>
      <webElementGuid>b771bc1b-da1a-452b-b83c-beeb9b6895eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[1]</value>
      <webElementGuid>adf2c2fe-e891-49c4-ab42-684e828535b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::li[1]</value>
      <webElementGuid>f053e58d-2282-47df-b734-9cc2b16b7543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>120b2797-64ba-414a-9d8a-c6a19adaabbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'f02f6b80-cf00-4e48-b884-1a5c2274b518-Yes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>983ea95a-2806-4fe0-be98-3f0c32f3c512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
