<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Here are listed the test cases where the User who is trying to register is already registered.</description>
   <name>Duplicated Registrations</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b82cdab4-bc4f-4199-8a8a-b0e96225bf57</testSuiteGuid>
   <testCaseLink>
      <guid>779c3cf0-4b07-4c3c-a0f3-7f09d02c5d29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - US Citizen - Email-SSN Duplicated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7921acd-df9e-4a9a-bd73-d1a021bf83ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>528b66d6-b585-4a98-bd2e-1f70465e86a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>025b7e82-593a-4d53-8a19-e8f38ae9a0c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>446dec11-c803-41b4-9b8f-56e9674e3fcb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5329ef2-1346-418f-ad84-abff028cb8f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - No Citizen - Email-I94 Duplicated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15110820-85fa-4da5-9b59-2cf3d9c70ffa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d208e6d-4188-400c-9db3-9ea60cd614f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>201b00ef-86de-4428-b484-d870f61008b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d39c27-68a8-414f-a8f5-107c737ffbfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d9098ce-923e-4145-84e2-4b66730af5f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - No Citizen - Email-AlienRegistrationNum Duplicated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9f2be25-c204-44de-992b-799cd6006f84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>085cb172-7860-431b-bb0e-30122faf768a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f85fa27-c614-4a4e-a466-2c560de4abeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a661c61-8886-465f-bc93-b69bc8f90c3d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c977f9e-ce54-4272-b5b9-0f787cc3ab41</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - Name criteria matches - No Citizen - Email-AlienRegistrationNum Duplicated - redirect to forgotten password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c732cec0-f99a-4ca2-8fdf-097c2ea93780</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - Name criteria matches - No Citizen - Email-I94 Duplicated - redirect to forgotten password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>db53d392-7a4d-4cd5-a31a-9e1b5b9ab23a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - Name criteria matches - US Citizen - Email-SSN Duplicated- redirect to forgotten password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f9714e64-e126-4813-858f-576251248dd8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - Same info as an existing record - Last name different - US Citizen - redirect to forgotten password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2d538fb7-2b0c-4c11-b41e-0b65f8324419</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - US Citizen - Duplicated Information, Email with variation - redirect to forgotten password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd1ca26f-c8c9-472d-aa88-beb0fa7a7a18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e1b9180-1379-450d-a4e2-f76486844298</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba12b837-1020-4be9-9058-3c6982824d0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e93a4ba3-6190-443e-8947-d829575a0e7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>374467eb-16d4-412d-888e-c4f0e806dcdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - US Citizen - Duplicated Information, first name uses a nick name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b4e38bc-3c03-4e3e-be6b-51e55b8864e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>335fd55d-a432-4d2a-91c2-9705fb3bfd68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88886f6c-07e3-4c67-9a3d-a607e996de33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14fa4c2c-88e7-42b4-ad63-872a28f2f243</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8ea7338-8b77-46f4-8320-10e28d9e38bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - US Citizen - Duplicated Information, First Name with variation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c24c514a-5947-41a6-861d-e597c0d4380b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa3f0be2-ccff-40ae-a023-774b075bc65b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b96c606-1f2e-4e75-be59-d216e60cef4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73d04114-4ab6-4b2a-b45a-711797486eef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b6ba5f9-7334-487d-b57e-63fea871062a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - US Citizen - Duplicated Information, slightly different DOB</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>123e55f5-7c04-4a02-b054-1f503b58b354</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>454cb766-afe5-4ba2-9b9f-364ac63a720d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b65fe60-4798-4254-8978-b2aa4860ba77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e265c0a9-db7f-4eb9-a672-ecff5fe7347c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64e8d7ce-f1ec-42a8-8ef9-62bbbb7379b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - User cease and desist - US Citizen - Random Nickname - Duplicated Last Name - contact DHHS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6fcdea7f-aea9-45f0-8b17-b48d6737ed47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - User cease and desist - US Citizen - Sounds like first name - Duplicated Last Name - contact DHH</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
