<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Registration Users Not Citizen</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>82a76103-4d47-4385-84b8-66268270fe0c</testSuiteGuid>
   <testCaseLink>
      <guid>81640ffe-1ae7-4cac-860e-1f8f12978f6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Successful - No Citizen - With Alien Registration ID</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eba8ac8c-98b4-44d5-ac6b-5fba1f863445</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f203b0c6-3480-497b-a68c-e333263a44f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4addc7bd-f931-469b-a6d4-f8d94bb04c10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7205454b-62d5-48b1-a913-678265ad8308</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ba36590-e0d5-46b0-b6d5-a779fd1e92fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Reset Password and Complete Registration Process</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5ecc7446-8ac9-4199-b4ae-b2f749a0d5ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Verify Unique Individual Record Created (via API)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>825bb195-8414-44c7-a132-142b18bfb566</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Successful - No Citizen - With I94</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ba6e432-a348-4e13-a0ba-64082e3ed953</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>585a1dfb-2161-48ce-87b4-c0d60aac9a08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2037a4c5-6723-420e-9c01-cc897ad50517</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>996573c4-e167-47aa-81bd-0f9de960c12a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Reset Password and Complete Registration Process</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b7e300ed-33c3-497e-9541-6f2f8b11fe09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Verify Unique Individual Record Created (via API)</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
