<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Registration of User who already exist on the System</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>33fb9918-20a5-448a-aad9-2bd032c0ff69</testSuiteGuid>
   <testCaseLink>
      <guid>b7744a75-bac9-4ca5-b48b-db8086f2b4da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Successful - No Citizen - I94-Email exist on the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21dfb433-d699-4c45-81f8-3e3d46d5ee5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a630131c-f2f3-4da4-a4c5-75aea3574c50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>307a3b36-2176-469a-b64b-1bd129ddd3a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35c6e649-7f2b-45cf-ad70-19b0e83bf9a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ce1be89-c614-4678-be84-8a607cd47ce7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Reset Password and Complete Registration Process</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7b6c0c58-8947-45ae-a476-3fc41ffcd2a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Verify Unique Individual Record Created (via API)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b314799f-e098-4a3f-a153-770e638c3fdf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Successful - No Citizen - Alien Registration Num-Email exist on the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d428050-0287-4cda-a2fd-9f041d26c727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>205971c2-76a7-450f-9130-68c08dbc6ea7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24f440ab-662e-4ea1-9a22-716c1443e2a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9d40721-ee00-4322-a040-adac1ab675b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f8e337e-9815-4aa0-9dc1-292955e8fe1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Reset Password and Complete Registration Process</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>38d1d061-4d29-40f1-999b-3d818b56fffa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Verify Unique Individual Record Created (via API)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>507dff04-443f-447d-a761-c64a63a70614</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Successful - US Citizen - SSN-Email exist on the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ffd8e03-0dad-4987-a05c-603c9bd1034e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>beeb7d8c-bf11-486b-ac21-da43e1bcaeeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a5f12f9-257a-44d2-9bae-f2e31295eb25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae052906-1429-49aa-9fc8-f9d460d3e7ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bb2217e-9677-4bc7-a22b-00081dbfdd69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Reset Password and Complete Registration Process</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>475298c5-6bfc-4e93-854f-7f36527cded5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Verify Unique Individual Record Created (via API)</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
