<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Nebraska</name>
   <tag></tag>
   <elementGuidId>ba0513bd-f541-459f-a763-ec5fbb79fc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acefd3c2-f225-44b7-b76f-bebe9501c4cf-NE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ba855ad9-aba7-4e13-89f6-30d7eb7b02a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d8ab23bf-87e7-4a61-93a6-67b618f751e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-selected ng-star-inserted</value>
      <webElementGuid>b3b78920-d156-4b3a-ac4c-1c1200a368a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acefd3c2-f225-44b7-b76f-bebe9501c4cf-NE</value>
      <webElementGuid>1a86dc94-1374-4fd6-8504-980ef05472cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3536de02-def6-4e6a-a568-62fe57d9e664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8f03ea5-79a2-48af-8ceb-9062b841a9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nebraska</value>
      <webElementGuid>551dc532-4a82-4969-ae63-485882e56df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acefd3c2-f225-44b7-b76f-bebe9501c4cf-NE&quot;)</value>
      <webElementGuid>cdac9bf2-2acf-417d-975e-c17e0dad5dcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='acefd3c2-f225-44b7-b76f-bebe9501c4cf-NE']</value>
      <webElementGuid>97892231-8ee2-4348-a77b-174132e08bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='023ed79a-c34b-4e32-aaff-e1ab357797a2']/li</value>
      <webElementGuid>76462a45-7f28-460e-9d92-94c69c00b090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[6]/following::li[1]</value>
      <webElementGuid>41f2c26d-39ae-4353-b802-e20f3eb1573c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font Family'])[3]/following::li[1]</value>
      <webElementGuid>f6ea39bb-e40b-466f-b649-9bb9ff990a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alabama'])[1]/preceding::li[1]</value>
      <webElementGuid>31bd7e4d-1b20-4555-855a-a68d9dd88ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alaska'])[1]/preceding::li[2]</value>
      <webElementGuid>5aef94fe-e227-4163-a2b4-4a69c779cdf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>9ed56a32-8d58-4c75-9138-11d4bd8bf58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'acefd3c2-f225-44b7-b76f-bebe9501c4cf-NE' and (text() = 'Nebraska' or . = 'Nebraska')]</value>
      <webElementGuid>489821e7-8b4c-40e2-9ea7-4897d967f610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
