<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Action Other State</name>
   <tag></tag>
   <elementGuidId>d6b9d923-efc1-4678-9cf1-e3d9b0ee213e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Action Other State']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fc201ecb-862a-432b-a96c-3314c2734818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d6130676-81e3-44cb-8272-d0f132cc9477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>b9a37065-d115-4b73-910a-9dcdc0396b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Action Other State</value>
      <webElementGuid>be4756b3-9417-4bce-b299-d730bec75233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a1a3b663-025f-428f-a8f7-c61c1f8fd433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>4ac68aae-7161-4b9e-9fce-3011a1b81db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Action Other State</value>
      <webElementGuid>9804d2c7-1aa9-408b-b0b5-2a24372209a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Action Other State&quot;)</value>
      <webElementGuid>5f704e0d-164d-4364-a2ac-b8878dc9a9d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Action Other State']</value>
      <webElementGuid>612e1e7a-2536-47ac-b2d7-e08185979959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='2f8ceed8-e399-4d24-a66a-a212ff879910']/li[7]</value>
      <webElementGuid>64fc49db-c3d4-478a-9c85-47f6f905fc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discipline'])[1]/following::li[1]</value>
      <webElementGuid>aa23a7a2-b00a-4d25-8c56-e70e4cbc7438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WDD-2. Inspection Reason'])[1]/following::li[2]</value>
      <webElementGuid>bb0fef7b-d89d-4328-9f15-166d5153af26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action Pending'])[1]/preceding::li[1]</value>
      <webElementGuid>b58b03b6-254f-4ce9-8e28-a402184b7eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrative Penalty Outstanding'])[1]/preceding::li[2]</value>
      <webElementGuid>c24c67b0-97a9-499b-ad46-191058381f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Action Other State']/parent::*</value>
      <webElementGuid>e9fcd826-8dec-47c8-acfe-c6980c714845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[7]</value>
      <webElementGuid>4b4d3c8b-b03f-4387-a99e-a36793f703b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Action Other State' and (text() = 'Action Other State' or . = 'Action Other State')]</value>
      <webElementGuid>30688881-a920-4166-93b9-76bb3dab5fc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
