<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Discipline</name>
   <tag></tag>
   <elementGuidId>5087dd80-234f-4f6c-9e47-4730f73c1561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Discipline']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Discipline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c642f863-edda-4833-860b-33a8367d042c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>52198286-4204-4919-9b2c-a181e0dd2771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>50980bcd-2289-4a1a-b24c-0c2bc88b37d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Discipline</value>
      <webElementGuid>a5254356-7add-4d28-94dc-93c5941daf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8083a97d-b7ba-492b-9c90-3ca3a6cad8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1b96d25a-cfc1-4975-a2f2-efb74c017548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Discipline</value>
      <webElementGuid>33798704-accd-4fa5-952b-d11aee2198ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Discipline&quot;)</value>
      <webElementGuid>28b0301c-dd0c-4e52-867b-b67723200859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Discipline']</value>
      <webElementGuid>1e48ea42-41ef-4600-93dc-d3572560db2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='2f8ceed8-e399-4d24-a66a-a212ff879910']/li[6]</value>
      <webElementGuid>ada0ce0c-d005-474e-974d-4f8d583ed026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WDD-2. Inspection Reason'])[1]/following::li[1]</value>
      <webElementGuid>b7b61cbf-0413-4125-a8d9-c8ce5f3e0678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEP - changed school'])[1]/following::li[2]</value>
      <webElementGuid>db6c516f-5664-41fd-8046-d791a14cb2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action Other State'])[1]/preceding::li[1]</value>
      <webElementGuid>fc64f4aa-364d-424c-8753-f20979fd53f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action Pending'])[1]/preceding::li[2]</value>
      <webElementGuid>5a246840-8ca0-4f73-bf1f-becacf510072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Discipline']/parent::*</value>
      <webElementGuid>5e0eb35f-348a-4d18-9926-376846cc1d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[6]</value>
      <webElementGuid>53786ce3-a8e4-4485-a57f-3a7fbb3d489f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-Discipline' and (text() = 'Discipline' or . = 'Discipline')]</value>
      <webElementGuid>f283e677-f9d8-490f-b012-340c7c473cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
