<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_TEP - changed school</name>
   <tag></tag>
   <elementGuidId>b955f958-e427-47ef-b488-303fe2f2a642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-TEP - changed school']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>54d78efc-8016-4891-8eae-6f27b0a5296e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>475a3419-2d30-4dae-9f66-9b9e5f81e986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>fdf17bbc-5826-46f9-8aad-6fe6d9321759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-TEP - changed school</value>
      <webElementGuid>cd9dc32b-0b70-441c-ac5b-e8a2c1fd4ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>80ab3db6-0012-4bac-9db8-2be609060768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0e3a12d9-cbd3-4c94-90a6-398ca65809f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEP - changed school</value>
      <webElementGuid>b7449836-b72d-4f26-8cde-31ee441d242b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-TEP - changed school&quot;)</value>
      <webElementGuid>459266e2-09c4-47dd-9a9d-e1a69631b05b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-TEP - changed school']</value>
      <webElementGuid>82342dcd-8d4f-4d2c-b2d0-92456179a3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='2f8ceed8-e399-4d24-a66a-a212ff879910']/li[4]</value>
      <webElementGuid>41a13987-f38e-47bf-b849-8778ede945dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surrender of Lic in lieu of discipline'])[1]/following::li[1]</value>
      <webElementGuid>23583e5a-58b3-42e8-b643-ce373dda4597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedation - Renewed Dentist License'])[1]/following::li[2]</value>
      <webElementGuid>0fca191f-6d68-4519-a7ca-51739021d98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WDD-2. Inspection Reason'])[1]/preceding::li[1]</value>
      <webElementGuid>bea42e4a-f336-47aa-bf0c-065580bb3729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discipline'])[1]/preceding::li[2]</value>
      <webElementGuid>fd198b42-bf3f-4fc4-9722-a96fa5898411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEP - changed school']/parent::*</value>
      <webElementGuid>40746161-8ede-4ab8-941a-be20414845b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]</value>
      <webElementGuid>4a7d7470-af31-4171-95f9-999cd9c0c05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '1e89c9d1-c909-4cbe-b42d-a5b29bdfcea6-TEP - changed school' and (text() = 'TEP - changed school' or . = 'TEP - changed school')]</value>
      <webElementGuid>85a9329e-8a36-4bee-95b4-35445962d192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
