<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_License Type</name>
   <tag></tag>
   <elementGuidId>04be21c1-3767-4ccc-bcec-4f75a3bd6941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div/div/div/div/table/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>dx-col-63</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Physical Therapist</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboardViewer&quot;)/div[@class=&quot;dx-dashboard-widget-container dx-dashboard-control dx-dashboard-typography dx-dashboard-theme dx-viewport dx-designer-viewport dx-color-scheme-light&quot;]/div[@class=&quot;dx-dashboard-surface&quot;]/div[@class=&quot;dx-dashboard-viewer-content&quot;]/dashboard-viewer[@class=&quot;dx-dashboard-viewer dx-dashboard-container&quot;]/dx-layout-item[@class=&quot;dx-layout-item dx-layout-root&quot;]/div[@class=&quot;dx-layout-item-wrapper&quot;]/div[@class=&quot;dx-layout&quot;]/div[@class=&quot;dx-layout-group&quot;]/dx-layout-item[@class=&quot;dx-layout-item&quot;]/div[@class=&quot;dx-layout-item-wrapper&quot;]/div[@class=&quot;dx-layout&quot;]/div[@class=&quot;dx-layout-group&quot;]/dx-layout-item[@class=&quot;dx-layout-item&quot;]/div[@class=&quot;dx-layout-item-wrapper&quot;]/div[@class=&quot;dx-layout&quot;]/div[@class=&quot;dx-layout-group&quot;]/dx-layout-item[@class=&quot;dx-layout-item&quot;]/div[@class=&quot;dx-layout-item-wrapper&quot;]/dx-dashboard-layout-group[1]/div[2]/div[@class=&quot;dx-layout&quot;]/div[@class=&quot;dx-layout-group&quot;]/dx-layout-item[@class=&quot;dx-layout-item&quot;]/div[@class=&quot;dx-layout-item-wrapper&quot;]/div[@class=&quot;dx-layout-item-container dx-dashboard-item-container dx-dashboard-group-item-child&quot;]/div[@class=&quot;dx-dashboard-item dx-dashboard-simple-border dx-widget dx-visibility-change-handler&quot;]/div[@class=&quot;dx-datagrid dx-gridbase-container&quot;]/div[@class=&quot;dx-datagrid-rowsview dx-datagrid-nowrap dx-scrollable dx-visibility-change-handler dx-scrollable-both dx-scrollable-simulated&quot;]/div[@class=&quot;dx-scrollable-wrapper&quot;]/div[@class=&quot;dx-scrollable-container&quot;]/div[@class=&quot;dx-scrollable-content&quot;]/div[@class=&quot;dx-datagrid-content&quot;]/table[@class=&quot;dx-datagrid-table dx-datagrid-table-fixed&quot;]/tbody[1]/tr[@class=&quot;dx-row dx-data-row dx-row-lines dx-column-lines&quot;]/td[3]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardViewer']/div/div[5]/div/dashboard-viewer/dx-layout-item/div/div/div/dx-layout-item/div/div/div/dx-layout-item/div/div/div[2]/dx-layout-item/div/dx-dashboard-layout-group/div[2]/div/div/dx-layout-item/div/div/div[3]/div/div[6]/div/div/div/div/table/tbody/tr/td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Physical Therapy'])[1]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Application'])[1]/following::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submitted'])[1]/preceding::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The grid has no data.'])[1]/preceding::td[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Physical Therapist']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/table/tbody/tr/td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Physical Therapist' or . = 'Physical Therapist')]</value>
   </webElementXpaths>
</WebElementEntity>
