<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_State - Arizona</name>
   <tag></tag>
   <elementGuidId>e10e0e82-4685-4d3c-8786-db9edd63c0a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#949571ad-7bb9-4d30-940d-28e8c72234b2-AZ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Arizona']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2d514ff8-2289-4e81-899c-dd90cee6fded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bac2c27e-f30c-4d74-8594-fcaad66dafd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>18d25bd0-9212-460f-afba-34de3834ee12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>949571ad-7bb9-4d30-940d-28e8c72234b2-AZ</value>
      <webElementGuid>6e553bdc-7486-4914-bec4-c5f8c81495d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fa12e171-df2c-4795-acb0-e1f9afcf7efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a74d9e1e-129c-42b5-bd8e-8e1f1f08778b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arizona</value>
      <webElementGuid>95e62547-76e2-493a-a101-68463f78022f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;949571ad-7bb9-4d30-940d-28e8c72234b2-AZ&quot;)</value>
      <webElementGuid>ffba8a56-5adb-4176-a687-ffde070f65de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='949571ad-7bb9-4d30-940d-28e8c72234b2-AZ']</value>
      <webElementGuid>ae476e2e-b5af-4e0c-ae0a-aeca012a4dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='e3ab24ca-285a-4d35-9837-9af1c3c5b82a']/li[3]</value>
      <webElementGuid>4daaf82c-5b27-4089-8567-93367ceefd2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alaska'])[1]/following::li[1]</value>
      <webElementGuid>e5b9cd75-4c9b-48b5-a9de-e4bf367db294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alabama'])[1]/following::li[2]</value>
      <webElementGuid>7372446a-fbd8-40c9-ba73-41b958265063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arkansas'])[1]/preceding::li[1]</value>
      <webElementGuid>219f0434-8659-4838-876d-12be0daa9d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='California'])[1]/preceding::li[2]</value>
      <webElementGuid>0a58ea3a-a235-4de2-bceb-de834a2e57f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Arizona']/parent::*</value>
      <webElementGuid>4073b384-8454-4b19-a3e8-9dceab246a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>8d152ed0-7f06-4536-8990-041a3c597188</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
