<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_does not contain_ctl00ContentBodyctrlPanelHolderctl0ctrlAdvancedFilter2dlCriteriactl01txtListCriteria</name>
   <tag></tag>
   <elementGuidId>1cdf6569-95cb-4f74-8fd1-9b02bee23aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentBody_ctrlPanelHolder_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_txtListCriteria']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentBody_ctrlPanelHolder_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_txtListCriteria</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentBody_ctrlPanelHolder_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_txtListCriteria</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentBody$ctrlPanelHolder$ctl0$ctrlAdvancedFilter2$dlCriteria$ctl01$txtListCriteria</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>riTextBox riFocused radTextCriteria riHover radTextCriteria</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Criteria</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if ((event.which &amp;&amp; event.which == 13) || (event.keyCode &amp;&amp; event.keyCode == 13)) { try {$('#ctl00_ContentBody_ctrlPanelHolder_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_txtListCriteria').blur().focus(); $find('ctl00_ContentBody_ctrlPanelHolder_ctl0_ctrlAdvancedFilter2_btnSearch').click()}catch(e) {}}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PR</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentBody_ctrlPanelHolder_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_txtListCriteria&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentBody_ctrlPanelHolder_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_txtListCriteria']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ContentBody_ctrlPanelHolder_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_txtListCriteria_wrapper']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentBody_ctrlPanelHolder_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_txtListCriteria' and @name = 'ctl00$ContentBody$ctrlPanelHolder$ctl0$ctrlAdvancedFilter2$dlCriteria$ctl01$txtListCriteria' and @title = 'Criteria' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
