<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply for aLicense (1)</name>
   <tag></tag>
   <elementGuidId>e5620ee0-0bfd-40ef-9f12-cbbfbfdb0430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Apply for a
							License')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p > a[alt=&quot;Apply for a License&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://vv5qa.visualvault.com/app/NEDHHS/LIS/formdetails?formid=6089cd93-634c-ec11-a9d3-e4a99b52c98f&amp;xcdid=0ad3e4a9-0bb8-eb11-81f9-f95f35fde26e&amp;xcid=f7abab70-0bb8-eb11-81f9-f95f35fde26e&amp;hidemenu=true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>opener</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Apply for a License</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply for a
							License
					</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;icon-div&quot;]/p[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Apply for a
							License')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://vv5qa.visualvault.com/app/NEDHHS/LIS/formdetails?formid=6089cd93-634c-ec11-a9d3-e4a99b52c98f&amp;xcdid=0ad3e4a9-0bb8-eb11-81f9-f95f35fde26e&amp;xcid=f7abab70-0bb8-eb11-81f9-f95f35fde26e&amp;hidemenu=true')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://vv5qa.visualvault.com/app/NEDHHS/LIS/formdetails?formid=6089cd93-634c-ec11-a9d3-e4a99b52c98f&amp;xcdid=0ad3e4a9-0bb8-eb11-81f9-f95f35fde26e&amp;xcid=f7abab70-0bb8-eb11-81f9-f95f35fde26e&amp;hidemenu=true' and @alt = 'Apply for a License' and (text() = 'Apply for a
							License
					' or . = 'Apply for a
							License
					')]</value>
   </webElementXpaths>
</WebElementEntity>
