<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_No</name>
   <tag></tag>
   <elementGuidId>f52f1c0c-4f7c-4138-8065-235b7fb512b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#01afa747-abd0-449d-8cac-aa463cfd379f-No</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4f64941b-c6f9-41c5-8440-76b968830786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ac0f5de3-2c7b-4d79-84be-be74c8344806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>bf0aa39a-e539-46f0-b1ec-fea73c14abf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>01afa747-abd0-449d-8cac-aa463cfd379f-No</value>
      <webElementGuid>9753f2e1-083d-4961-9708-c4f64e5fd71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fcdade54-d818-4975-bbe8-896f4a4ed305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>71e19fb3-0a56-4890-b171-e127c189afb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>387a596f-7711-49cb-9a6e-8965efbec970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;01afa747-abd0-449d-8cac-aa463cfd379f-No&quot;)</value>
      <webElementGuid>49e882e1-1100-4fe8-845e-dad02561420e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='01afa747-abd0-449d-8cac-aa463cfd379f-No']</value>
      <webElementGuid>2a04ae28-e260-4d13-a9fe-27e6ddb825c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cd9b4a82-b002-426a-8ac1-a7935c54173a']/li[2]</value>
      <webElementGuid>74b16a90-b3b9-4a64-83dd-ad25228f3616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[78]/following::li[1]</value>
      <webElementGuid>8a5a731d-7395-4636-a239-d77581908c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add License'])[1]/following::li[2]</value>
      <webElementGuid>efe5ad19-853f-40e5-83b6-129cf4efd827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[5]/preceding::li[1]</value>
      <webElementGuid>888a1672-351c-4c0f-8a44-29cd411c6645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[2]</value>
      <webElementGuid>a4fed7a0-1694-4208-ba07-7d52a1e7836c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>181a7b5a-0b35-4faa-bfd9-2ab422fa1900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '01afa747-abd0-449d-8cac-aa463cfd379f-No' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>c46edbb0-064a-4ceb-8d43-aef2c6f5fc66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
