<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IllnessDisability_Active Military Competency Waiver</name>
   <tag></tag>
   <elementGuidId>514baafd-a4c2-4775-ba13-f788d3389fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Active Military Competency Waiver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93ceacd3-d28a-4b70-8d82-7a637d753d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>58b73056-23b9-4b7b-ace1-efac16f78338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Active Military Competency Waiver</value>
      <webElementGuid>401b0b76-52e3-437b-b940-dac0486a88d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>a4014afc-1ee8-4bca-bfae-f46d17a9c9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Active Military Competency Waiver</value>
      <webElementGuid>918d273e-2733-4f3b-97f8-dddfa5c0961a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldtype</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bb6bd10b-b873-406d-8c8a-27d2bf1a33d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldname</name>
      <type>Main</type>
      <value>Active Military Competency Waiver</value>
      <webElementGuid>519ff9bd-6af0-4753-a79d-78b2be5cbc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldvalueid</name>
      <type>Main</type>
      <value>529452e0-ec49-438e-fcbf-f220f6609dc1</value>
      <webElementGuid>14b9d954-c983-4600-9f0c-ce0e616ca8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c72c3ad7-89f0-40cb-8193-b4ba0668ff9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Active Military Competency Waiver&quot;)</value>
      <webElementGuid>2c5a67a5-0502-4613-8a1a-51160d73248e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Active Military Competency Waiver']</value>
      <webElementGuid>62588066-77d7-45c7-adb2-fcd9b48b5ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/viewer-tab-form/div/div[2]/div/div/div[247]/div/div/input</value>
      <webElementGuid>2801fc46-b1b8-450c-913c-60030b1e9dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[247]/div/div/input</value>
      <webElementGuid>943ebc2c-ab46-4094-891b-761cbb61cde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @title = 'Active Military Competency Waiver' and @id = 'Active Military Competency Waiver']</value>
      <webElementGuid>485ba7af-5537-49fe-9e17-7e167c7b2536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
