<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description</name>
   <tag></tag>
   <elementGuidId>ffe64832-ba19-4144-a2b2-55f55827f442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Continuing Competency Waiver Dynamic Text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e9bbe2e8-7867-4537-8a15-1c3e07909d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28935af1-8590-4da0-ae1f-824a6e55d0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm_editor</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>363e08b5-11c5-460f-b113-7fb94f4a7523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-grammarly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>04bd0871-558b-4ae8-8c28-83aaf8009c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Continuing Competency Waiver Dynamic Text</value>
      <webElementGuid>c771d7ed-a5f4-4cfb-bd97-e254adc6510c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>18568eed-3c6a-41b3-adc1-5a10344e32e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3001</value>
      <webElementGuid>1bee04d4-3251-4ac1-9cfe-58c2121b4982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ea823838-78c0-421a-acc2-d16664f38a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Continuing Competency Waiver Dynamic Text</value>
      <webElementGuid>49db58d6-48b7-4e4a-85a3-9f3f54f50b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldtype</name>
      <type>Main</type>
      <value>multilinetextbox</value>
      <webElementGuid>2a4c813a-b726-4048-90f6-34da0f99d2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldname</name>
      <type>Main</type>
      <value>Continuing Competency Waiver Dynamic Text</value>
      <webElementGuid>a3e16652-95b8-4be9-a4f6-51fd7856c225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldvalueid</name>
      <type>Main</type>
      <value>c8c36d16-9e9d-dd91-2930-937651698f4d</value>
      <webElementGuid>b941d9a9-4263-4f80-8867-bb18d8a928d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fd-textarea ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>fa21eac8-faae-4c62-9164-7829b82f3c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Continuing Competency Waiver Dynamic Text&quot;)</value>
      <webElementGuid>3f69ee92-8044-4143-9df0-a316a19030cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Continuing Competency Waiver Dynamic Text']</value>
      <webElementGuid>af1ae53e-feab-4f64-923e-5715862e00f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/viewer-tab-form/div/div[2]/div/div/div[240]/div/textarea</value>
      <webElementGuid>84cb8e29-0d64-44f4-8777-da759bb59ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[240]/div/textarea</value>
      <webElementGuid>85b38ceb-7997-4eb1-a95f-ca9c972f7450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@title = 'Continuing Competency Waiver Dynamic Text' and @id = 'Continuing Competency Waiver Dynamic Text']</value>
      <webElementGuid>c10bc592-8c0d-4d40-9a1a-95fedfddd432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
