<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_No</name>
   <tag></tag>
   <elementGuidId>32a3776c-525d-492a-99ab-a8286378751d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='afba650b-62f7-41ff-bc4a-e3fbeaadcccd-No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#afba650b-62f7-41ff-bc4a-e3fbeaadcccd-No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2ce733da-df62-4f64-b5ec-796c345c3ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e8bcffa5-2163-4748-8825-318e0792722d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>e5bccad0-4524-4eee-b461-20091e32ec87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>afba650b-62f7-41ff-bc4a-e3fbeaadcccd-No</value>
      <webElementGuid>04f4d36e-667a-491d-93bc-9ae3f5961e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>84a3d472-ec94-4905-9fea-c7eea23db217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3c3fc8b5-d7c4-4e3b-96ba-774d079c094c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>ca5f89e0-069e-4bf7-a47a-ba3016de7c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;afba650b-62f7-41ff-bc4a-e3fbeaadcccd-No&quot;)</value>
      <webElementGuid>b3cf9da6-797d-4728-a580-8fc50f44c02e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='afba650b-62f7-41ff-bc4a-e3fbeaadcccd-No']</value>
      <webElementGuid>b5887cff-c47b-4427-aa48-2e4c463528dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='0b8eda56-a12c-4f96-a0d3-460bd4b6c962']/li[2]</value>
      <webElementGuid>78bf2796-79b9-4d55-b8f0-5dca3ecaf33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[70]/following::li[1]</value>
      <webElementGuid>7b1b8745-acd6-4936-9461-4ba1eddf0b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add License'])[1]/following::li[2]</value>
      <webElementGuid>1c2c3a72-0f9b-4a7a-a36b-e79982c11390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[6]/preceding::li[1]</value>
      <webElementGuid>8b487fbd-dcd2-4563-ab15-6495011bcf62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::li[2]</value>
      <webElementGuid>d8d235dc-6466-489e-a4b2-0627c6d013db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>df24477e-cfbd-45b8-860f-45e60f8292e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'afba650b-62f7-41ff-bc4a-e3fbeaadcccd-No' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>507c872e-7b60-4b02-9f8e-371329bc2711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
