<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Yes</name>
   <tag></tag>
   <elementGuidId>aa4dead5-ca96-465a-9d5c-862e6d290ce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='afba650b-62f7-41ff-bc4a-e3fbeaadcccd-Yes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#afba650b-62f7-41ff-bc4a-e3fbeaadcccd-Yes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7965241a-0540-40e2-a960-adb26776e987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>47e90857-bddb-48b8-bcaf-2aa3f687541e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>64f0eaad-19ce-4a6e-b5de-7be8c2b55556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>afba650b-62f7-41ff-bc4a-e3fbeaadcccd-Yes</value>
      <webElementGuid>c27bc876-876b-4b77-affe-57b354fb25a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>26b79974-e8a3-434f-ae3c-3ae0cdce71a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>654ecbaf-6f03-46e9-b9ec-0e40b15cc218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>be193ed7-5d3b-4d91-9413-d5e512de2c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;afba650b-62f7-41ff-bc4a-e3fbeaadcccd-Yes&quot;)</value>
      <webElementGuid>f97fd513-124b-4822-9e5d-593fab8d4668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='afba650b-62f7-41ff-bc4a-e3fbeaadcccd-Yes']</value>
      <webElementGuid>a6599fa6-c08e-4cc5-a218-6c1fcd6406be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='0b8eda56-a12c-4f96-a0d3-460bd4b6c962']/li[3]</value>
      <webElementGuid>a2a23633-d4cf-40ce-990c-572a24448851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[8]/following::li[1]</value>
      <webElementGuid>e18ec22e-1c6a-481c-8768-657f918360f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[70]/following::li[2]</value>
      <webElementGuid>fc33a88e-d1f2-4dce-8e59-ffaa0fe461cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::li[1]</value>
      <webElementGuid>68b7228d-0bac-45b5-ab4a-f3fd24c73b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::li[1]</value>
      <webElementGuid>4aeb9584-14ff-40fb-835c-923bcc4391ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>74c897d6-93ca-4774-8138-be3be769c885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'afba650b-62f7-41ff-bc4a-e3fbeaadcccd-Yes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>a85d44a4-6582-44cf-9ba9-11bc7441998f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
