<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Low Income View Uploaded Documents</name>
   <tag></tag>
   <elementGuidId>09f86c54-31cc-449d-911c-4ae3a554027c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUploads1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnUploads1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aeb2afbf-966e-4ee7-93ca-70ad4e46d9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4ba563d-e5ac-4c0d-85c6-3324b1556e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>btnUploads1</value>
      <webElementGuid>ef7dd3f5-7d89-4d4c-8504-e64b786cc6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>516822b6-0893-415b-bf47-97b996a313c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUploads1</value>
      <webElementGuid>947b6cf6-5fea-41ca-83fb-a4872f1ba312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View Uploaded Documents</value>
      <webElementGuid>bf88e19d-87a3-4ec2-b0ce-2c5ccd171dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldtype</name>
      <type>Main</type>
      <value>formbutton</value>
      <webElementGuid>9af8249f-39eb-4744-98d8-dd56903df2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldname</name>
      <type>Main</type>
      <value>btnUploads1</value>
      <webElementGuid>a186bdf1-f5b9-4159-97db-f9ab25e96901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldvalueid</name>
      <type>Main</type>
      <value>c6643d25-a496-1901-3022-4883af1a0f8d</value>
      <webElementGuid>62056ed9-c033-4bbb-a0bf-76ea453cc7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-button k-button ng-star-inserted</value>
      <webElementGuid>80c338c4-b77d-434f-b3e7-e5c993e15310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>805b52ce-811c-42dd-b7cc-e4ee0ba3369c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>06e13ad7-ab2f-4bee-9deb-31fe518f5456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> View Uploaded Documents
</value>
      <webElementGuid>0ec3f649-0515-408a-8225-0d9b303538bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUploads1&quot;)</value>
      <webElementGuid>4e9617f1-1586-46b1-ae95-78babdfbeb65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnUploads1']</value>
      <webElementGuid>6f66c50e-c987-4cb3-8eb1-38ffd0513623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/viewer-tab-form/div/div[2]/div/div/div[97]/div/button</value>
      <webElementGuid>ec99274a-c4f1-4e86-abc9-8c888a690d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide documentation of household income and/or participation in federal assistance program:'])[1]/following::button[1]</value>
      <webElementGuid>275939ea-7f6c-472d-8c7d-2ec60d7610a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[16]/following::button[1]</value>
      <webElementGuid>4ccaf999-40f1-41bc-bc1c-1a8425bc784b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Military Family'])[1]/preceding::button[1]</value>
      <webElementGuid>6514036a-ca6f-4304-8ac3-00b2f731b9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide documentation of military service for yourself or family member:'])[2]/preceding::button[1]</value>
      <webElementGuid>1e8c4dcb-b3d3-4062-9bb2-26208827bf59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[97]/div/button</value>
      <webElementGuid>d7866a4c-69b1-418c-98be-b1f668ee5746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'btnUploads1' and @id = 'btnUploads1' and (text() = ' View Uploaded Documents
' or . = ' View Uploaded Documents
')]</value>
      <webElementGuid>67282242-f129-401b-b831-c2eeefdd2835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
