<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnUploadMilitaryFeeWaiver</name>
   <tag></tag>
   <elementGuidId>c02be23b-9257-4244-96a0-f046a10bff90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUploadMilitaryFeeWaiver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnUploadMilitaryFeeWaiver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0be68a74-25f5-4a6a-95e6-f54206900242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d457b39-18b4-46e3-8c98-8f7c321340bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96e58e5a-eb82-47f4-b546-cae9846b307a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>btnUploadMilitaryFeeWaiver</value>
      <webElementGuid>db5c058b-be8e-4733-af54-3bc1de831bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>8d7c83ac-371e-49b8-9284-7ca5c527f746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Upload Documents</value>
      <webElementGuid>b4c27d6c-d07f-45d1-9cab-ac310119dc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUploadMilitaryFeeWaiver</value>
      <webElementGuid>804ffd61-81b1-4bd2-b5de-d8338a106259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldtype</name>
      <type>Main</type>
      <value>uploadbutton</value>
      <webElementGuid>48d3c28d-561b-441c-9792-930df295e212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldname</name>
      <type>Main</type>
      <value>btnUploadMilitaryFeeWaiver</value>
      <webElementGuid>5410bb0f-4069-4c3d-be29-5feec7204e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldvalueid</name>
      <type>Main</type>
      <value>b908991b-49a0-83f3-3bc9-ef98a11c7cde</value>
      <webElementGuid>1de268dd-232d-48ec-9026-bc9016f2ae3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-button ng-star-inserted</value>
      <webElementGuid>6a4ab194-6b7e-48e6-ad32-388f62db4048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUploadMilitaryFeeWaiver&quot;)</value>
      <webElementGuid>6318ba64-b95e-4f7f-b919-962fda9782a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnUploadMilitaryFeeWaiver']</value>
      <webElementGuid>68a75501-af65-43c8-91e8-27f9a48cb690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/viewer-tab-form/div/div[2]/div/div/div[99]/div[2]/input</value>
      <webElementGuid>e0139a5f-8f7d-4328-bc70-49b2709732c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[99]/div[2]/input</value>
      <webElementGuid>f9fca5da-fc38-4fc2-a4eb-1fc36da6b151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'btnUploadMilitaryFeeWaiver' and @id = 'btnUploadMilitaryFeeWaiver']</value>
      <webElementGuid>8a350d4e-3550-4f99-a2f5-e6b00b15ddc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
