<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnUploadLowIncomeFeeWaiver</name>
   <tag></tag>
   <elementGuidId>98a743ae-e57f-4090-9485-c1197fd127f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUploadMilitaryFeeWaiver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnUploadLowIncomeDocuments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0fc6b4d-d981-4940-b168-7a8546d21d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>350278bd-fc98-4157-88af-d8ebb86ee56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebdf2087-b689-4434-aabe-a7a2fe6065f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>btnUploadMilitaryFeeWaiver</value>
      <webElementGuid>e5c1e51b-f999-4448-8793-0b6a5d347258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>d3fbb234-9ebe-4b57-a0da-23c52a6361a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Upload Documents</value>
      <webElementGuid>f3d0cf29-e787-47b3-95b4-e3893ebbdd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUploadMilitaryFeeWaiver</value>
      <webElementGuid>d9929746-5087-430b-ab4b-b0e1d17b1b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldtype</name>
      <type>Main</type>
      <value>uploadbutton</value>
      <webElementGuid>10d56c89-527e-4eee-b100-87be22bdcea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldname</name>
      <type>Main</type>
      <value>btnUploadMilitaryFeeWaiver</value>
      <webElementGuid>b2c93583-44cf-4db9-80c2-0d5ac82bbe09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldvalueid</name>
      <type>Main</type>
      <value>b908991b-49a0-83f3-3bc9-ef98a11c7cde</value>
      <webElementGuid>57fb3785-c043-4993-bd75-94d98929a611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-button ng-star-inserted</value>
      <webElementGuid>04b77953-01c9-44fb-9340-5495e02580db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUploadMilitaryFeeWaiver&quot;)</value>
      <webElementGuid>0b956301-6372-4e0e-b1d4-518ff7180005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnUploadLowIncomeDocuments']</value>
      <webElementGuid>fe7f0862-cb0c-49bb-a6c9-a706a1b67bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/viewer-tab-form/div/div[2]/div/div/div[96]/div[2]/input</value>
      <webElementGuid>dddb33eb-b0d9-4899-bb3d-0d2ca83e290e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[96]/div[2]/input</value>
      <webElementGuid>b6dda5e0-3a37-4bf8-8003-8f3f9116cc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'btnUploadLowIncomeDocuments' and @id = 'btnUploadLowIncomeDocuments']</value>
      <webElementGuid>0b46f592-9f4a-43bf-81bf-62838dd6f34a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
