<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Cosmetologist</name>
   <tag></tag>
   <elementGuidId>16013bf9-ec15-4ccc-81b9-9f328983a1e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Cosmetologist']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#17abab6a-ebb6-4a72-8afe-952103650803-Cosmetologist</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>050a5a05-aaab-4a92-a3b5-387003589f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>36372211-0f4c-4f4b-a095-bdd0abf74791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>a0ab3c29-d6b1-45ec-a3ee-c39e27588d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>17abab6a-ebb6-4a72-8afe-952103650803-Cosmetologist</value>
      <webElementGuid>4648f08d-228c-49fb-96f5-98d6c002e499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b095f3df-7d10-4bb3-b11d-e52d5908ca24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b4340889-ae14-494a-a3e5-2982991f564f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cosmetologist</value>
      <webElementGuid>ccc9cd62-9694-4ccc-b277-b93c2de90c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;17abab6a-ebb6-4a72-8afe-952103650803-Cosmetologist&quot;)</value>
      <webElementGuid>7e719e7a-91b4-45db-b318-f90f947df1b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='17abab6a-ebb6-4a72-8afe-952103650803-Cosmetologist']</value>
      <webElementGuid>97376096-e236-4cba-a4ab-666865647c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='4a94dd41-d4c2-4017-99b4-9e3db538a746']/li</value>
      <webElementGuid>a5af4b65-5502-4bfa-844d-ff34a4f36d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item'])[7]/following::li[1]</value>
      <webElementGuid>c381b7cc-e5a7-4ef4-9981-0d799999372d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Application Checkboxes:'])[1]/following::li[1]</value>
      <webElementGuid>81d6704b-c85e-45e4-b6cf-5419158cf4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cosmetology Instructor'])[1]/preceding::li[1]</value>
      <webElementGuid>f91a1cc4-4eb1-4190-b4c8-2e89575bda67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cosmetology Salon'])[1]/preceding::li[2]</value>
      <webElementGuid>2b1270fd-edd3-462b-bafd-93b806c47ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cosmetologist']/parent::*</value>
      <webElementGuid>9bca03d1-9846-4b76-b1f7-db03bd5504f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>771b0df9-90eb-4a12-992f-94cf122e675f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '17abab6a-ebb6-4a72-8afe-952103650803-Cosmetologist' and (text() = 'Cosmetologist' or . = 'Cosmetologist')]</value>
      <webElementGuid>3e4e8ec9-bcd9-4019-b2c7-ec20ef411186</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
