<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Cosmetology</name>
   <tag></tag>
   <elementGuidId>0a0aafb3-885f-42b3-8f0d-eef1170596fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Cosmetology']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#422c6b5f-3a16-459b-b7dd-a5816b7ca39e-Cosmetology</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8b60d489-bbc5-47c7-b85a-71e2ada6a93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cadce86f-8939-4889-8d72-8ea0ef829424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>4455b826-e6fc-46e6-8573-f76ece3c0bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>422c6b5f-3a16-459b-b7dd-a5816b7ca39e-Cosmetology</value>
      <webElementGuid>d14aada4-9095-4d54-85a0-283d4bc0817a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ecf0f267-ef0a-4924-a13d-76ec6c9a34f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>d315a422-74c8-4c81-9bb6-b2be9b51fd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cosmetology</value>
      <webElementGuid>a82248a2-8f24-401d-9269-742c9c764cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;422c6b5f-3a16-459b-b7dd-a5816b7ca39e-Cosmetology&quot;)</value>
      <webElementGuid>5614618a-550f-4415-bbaf-c0d7eea334bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='422c6b5f-3a16-459b-b7dd-a5816b7ca39e-Cosmetology']</value>
      <webElementGuid>2b58a589-b56e-4e9d-bd3b-a07dfd95e0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='fc956ed3-d18f-4291-9b44-53a51abae617']/li[13]</value>
      <webElementGuid>3c87095d-d34b-49e2-9a92-9b9d59884fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Controlled Substances'])[1]/following::li[1]</value>
      <webElementGuid>770b300e-ecc9-4c60-a03c-1888afe5afe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compulsive Gambling Counselor'])[1]/following::li[2]</value>
      <webElementGuid>5750bddd-f24e-405c-baad-c13d988a6242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crematory'])[1]/preceding::li[1]</value>
      <webElementGuid>f9992cbc-c992-430d-a7dc-059c57a44aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dentistry'])[1]/preceding::li[2]</value>
      <webElementGuid>e6a73888-629c-4d1d-8491-13e83e6a9359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cosmetology']/parent::*</value>
      <webElementGuid>c8a539e4-1d2f-4db1-aafd-fd464e456e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]</value>
      <webElementGuid>67395e8f-0561-4b02-814a-cd83af1f85d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '422c6b5f-3a16-459b-b7dd-a5816b7ca39e-Cosmetology' and (text() = 'Cosmetology' or . = 'Cosmetology')]</value>
      <webElementGuid>1afa61a5-6ea3-44b5-87f2-03978bef9dd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
