<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnUploadMilitarySpouse</name>
   <tag></tag>
   <elementGuidId>259e7354-8a81-4b9a-acc2-de86a9514de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUploadMilitaryFeeWaiver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnUploadMilitarySpouse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7565a4f3-6aa8-4654-a560-b440889a5e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12a2f733-361b-4d04-8006-ad097d62857c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a0752d0-06a5-4d19-a8dd-8cf28bf146a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>btnUploadMilitaryFeeWaiver</value>
      <webElementGuid>6b7cc00f-c876-489f-b049-b6df66952b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f805cb01-87ea-47f0-977b-70b19a6d1088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Upload Documents</value>
      <webElementGuid>660c2f74-c665-4db4-895f-77bd97c7d7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUploadMilitaryFeeWaiver</value>
      <webElementGuid>b4b07f60-da4f-4b4e-b00d-6bf3ad902eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldtype</name>
      <type>Main</type>
      <value>uploadbutton</value>
      <webElementGuid>b453eea4-9408-49dc-ae47-478172a788f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldname</name>
      <type>Main</type>
      <value>btnUploadMilitaryFeeWaiver</value>
      <webElementGuid>b82991cb-7af8-4f64-a3af-bdeab9b518fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vvfieldvalueid</name>
      <type>Main</type>
      <value>b908991b-49a0-83f3-3bc9-ef98a11c7cde</value>
      <webElementGuid>e96f11d2-1ad8-49d5-983c-d1cd13da988c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-button ng-star-inserted</value>
      <webElementGuid>42893099-be6c-48ed-9129-456fc89e2881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUploadMilitaryFeeWaiver&quot;)</value>
      <webElementGuid>ad053129-5444-4828-9760-c4cf76b7b032</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnUploadMilitarySpouse']</value>
      <webElementGuid>a3321573-f189-4c3b-882d-9fd6a154c59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/viewer-tab-form/div/div[2]/div/div/div[99]/div[2]/input</value>
      <webElementGuid>892de6d9-4ff4-433d-9f61-632629c33802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[99]/div[2]/input</value>
      <webElementGuid>dfec851d-ab90-4339-867c-ccf9bdd806ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'btnUploadMilitaryFeeWaiver' and @id = 'btnUploadMilitaryFeeWaiver']</value>
      <webElementGuid>0f9fae11-2b48-4d00-9e13-aab9f171a2f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
