<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select Search Criteria</name>
   <tag></tag>
   <elementGuidId>8ec1e684-224e-47cb-8620-536dc3c7c9a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentBody_2t5k_PCWEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_ddlLookIn_Arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/div/table/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentBody_2t5k_PCWEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_ddlLookIn_Arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentBody_2t5k_PCWEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_ddlLookIn_Arrow&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentBody_2t5k_PCWEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_ddlLookIn_Arrow']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentBody_2t5k_PCWEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ukL78fCoEeuCB55hMl16Ow_ctl0_ctrlAdvancedFilter2_dlCriteria_ctl01_ddlLookIn']/table/tbody/tr/td[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'select')])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='('])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[3]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Details'])[4]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/table/tbody/tr/td[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
