<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_temporary_License_Military_Spouse_Arrow</name>
   <tag></tag>
   <elementGuidId>cfa74ee9-eab0-4f28-b6fa-82e1f7f71567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//kendo-dropdownlist[@id='Military Spouse Temporary License']/span/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-a5a34b8f-b02f-464f-9ee8-5423806bf2bb > span.k-select > span.k-icon.k-i-arrow-s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>375b3c75-2e75-4bde-9ba0-aa438fe7d962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>abd8bfb7-f519-45d1-b38e-3e96056a5276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-s</value>
      <webElementGuid>e60e3cbe-c634-406e-b723-c58514a65ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-a5a34b8f-b02f-464f-9ee8-5423806bf2bb&quot;)/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-s&quot;]</value>
      <webElementGuid>1ba6a43e-71a2-4137-abe7-844f3c6fd013</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-a5a34b8f-b02f-464f-9ee8-5423806bf2bb']/span[2]/span</value>
      <webElementGuid>de443f7d-17d2-447d-aa3f-4c8d3f63c100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[61]/div[2]/div/kendo-dropdownlist/span/span[2]/span</value>
      <webElementGuid>efbcff4f-2ee1-496e-bfcc-b7cc256218c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
