<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_No</name>
   <tag></tag>
   <elementGuidId>9cc5b5c3-dc2f-4d16-9c11-8006a90334df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#80de2c32-eb7f-4ef6-94cd-b6557ac510ac</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>daba7eb3-b415-47a1-ae02-6e8b3ba308a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3ccba8c7-a5ec-4c67-9833-196f9c3c7ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>355019fe-8ec7-4058-a2e9-8e2383bf2945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>80de2c32-eb7f-4ef6-94cd-b6557ac510ac</value>
      <webElementGuid>3f4ef25e-ae46-4773-b740-62fcc74a53a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>db5c53f4-68a5-4c0d-adba-c229b5659a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;80de2c32-eb7f-4ef6-94cd-b6557ac510ac&quot;)</value>
      <webElementGuid>95c07abb-4903-4587-aa58-9a6797f8bb51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='80de2c32-eb7f-4ef6-94cd-b6557ac510ac']</value>
      <webElementGuid>178b8f0b-d4e8-4b48-a62b-23a441c56e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-a5a34b8f-b02f-464f-9ee8-5423806bf2bb']/span</value>
      <webElementGuid>a499a488-2aac-4af4-9e16-fb33234562ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[58]/following::span[2]</value>
      <webElementGuid>e09dd657-a903-43a7-9058-f92255c9e54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide documentation of military service for yourself or family member:'])[1]/preceding::span[3]</value>
      <webElementGuid>6a2da200-09fb-4681-a283-408128129c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Uploaded Documents'])[1]/preceding::span[3]</value>
      <webElementGuid>46934619-cbe2-49cc-9cb5-70fbb4b4681d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No']/parent::*</value>
      <webElementGuid>3a8c5ae8-75da-44ae-98c8-fdf8eaea4ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[61]/div[2]/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>1d4ef973-b55f-404b-8d9c-02250f1bf21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '80de2c32-eb7f-4ef6-94cd-b6557ac510ac' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>0b1496d1-4830-4e5f-af4a-005a41e98f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
