<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes</name>
   <tag></tag>
   <elementGuidId>b3dff38d-9ba2-45b6-981d-b022e136c9f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1fd64fe8-de0b-433e-9ef5-513cae07d2c5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd78aca8-2e4f-4eff-94a3-ba74f7592a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a4c67972-44e0-49dd-adcb-200e3c924ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>32ce8a5b-10f3-414c-bd3a-eaba527da7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1fd64fe8-de0b-433e-9ef5-513cae07d2c5</value>
      <webElementGuid>844d1838-5716-49c9-8a6a-b7d914957783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>feb59115-1c67-4abc-8b16-70ba0dd635f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1fd64fe8-de0b-433e-9ef5-513cae07d2c5&quot;)</value>
      <webElementGuid>f73efe07-44be-4503-b586-86f7c585fce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='1fd64fe8-de0b-433e-9ef5-513cae07d2c5']</value>
      <webElementGuid>146e77b0-54ec-4e25-a04c-bb30cac2b84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-a5a34b8f-b02f-464f-9ee8-5423806bf2bb']/span</value>
      <webElementGuid>99259465-fec5-4471-9dc1-f10bc3b14d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[58]/following::span[2]</value>
      <webElementGuid>28c1beb4-3b3b-4175-ad87-6f7d94865e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide documentation of military service for yourself or family member:'])[1]/preceding::span[3]</value>
      <webElementGuid>378dc225-4863-423c-9a0b-c7c1237cf723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Uploaded Documents'])[1]/preceding::span[3]</value>
      <webElementGuid>b865a467-750a-4889-bf7a-2402aa46efe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[61]/div[2]/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>5d76bfff-c09e-4344-bdf1-bf0c62833da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '1fd64fe8-de0b-433e-9ef5-513cae07d2c5' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>c1c3d5b9-46fc-47f1-87c5-03d2d55d756a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
