<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select License Type-arrow</name>
   <tag></tag>
   <elementGuidId>5c241b8d-7d5a-4679-bdc0-b65749d8a200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[162]/div[2]/div/kendo-dropdownlist/span/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-abe2242b-ee41-4194-aafa-719444ff03df > span.k-select > span.k-icon.k-i-arrow-s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-s</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-abe2242b-ee41-4194-aafa-719444ff03df&quot;)/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-s&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-abe2242b-ee41-4194-aafa-719444ff03df']/span[2]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[162]/div[2]/div/kendo-dropdownlist/span/span[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
