<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Open Task8</name>
   <tag></tag>
   <elementGuidId>3689f278-03d9-4191-9336-e926b67f9f19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RRCChecklist']/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr[8]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>835f9791-b9f8-4590-9286-beefd073546a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-cell-link ng-star-inserted</value>
      <webElementGuid>f985cd43-040b-4b67-8b3d-34a96ec3e07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open</value>
      <webElementGuid>10a17e8c-7637-4288-b491-39c021e7d914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RRCChecklist&quot;)/kendo-grid[@class=&quot;rrc-grid k-widget k-grid&quot;]/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;k-alt ng-star-inserted&quot;]/td[@class=&quot;d7ee98f5-668a-9963-5dc4-b042c46691da hAlignLeft vAlignMiddle ng-star-inserted&quot;]/a[@class=&quot;grid-cell-link ng-star-inserted&quot;]</value>
      <webElementGuid>2bdfb43d-8310-4622-ab7f-3fbcead7a7d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RRCChecklist']/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr[8]/td/a</value>
      <webElementGuid>284e8407-e44d-47f0-8b0a-46899a96dc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Open')])[8]</value>
      <webElementGuid>02e45584-6c24-4ad2-8e67-b82a2b793a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[14]/following::a[1]</value>
      <webElementGuid>049e3fc2-d2e8-44ad-9ef8-b35ebe9153ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[4]/following::a[1]</value>
      <webElementGuid>eaa598de-08ae-423a-b08b-cb293b11dc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unique Identifier for tcijw hgsov and license Physical Therapist'])[1]/preceding::a[1]</value>
      <webElementGuid>03bcfad1-e3b1-434a-be40-e8db611f9c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[3]/preceding::a[1]</value>
      <webElementGuid>5df7c9b3-e782-42c8-b789-2115e73a071e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/a</value>
      <webElementGuid>0aa0e571-048b-4ce9-905a-ee504b7ead14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
