<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Exam Date</name>
   <tag></tag>
   <elementGuidId>46b90648-2285-4b24-b6b3-b0e7ae1e3f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Exam Date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>872a0b2b-0d72-4c78-9c64-a3e56f4e111c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a776a32-0807-42dd-8ecd-61022f6fa9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Exam Date</value>
      <webElementGuid>3ea3bac2-63f2-4b95-9f25-ec646e477bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>059f3537-4d52-42df-96d6-2a300d1f00e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Exam Date</value>
      <webElementGuid>3ac8427d-f0ac-47c1-a064-5dc3bb60ca2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/dd/yyyy</value>
      <webElementGuid>1759ade2-682e-45e6-9849-a2da9c16d44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Exam Date</value>
      <webElementGuid>208c794d-cc83-4705-a1cd-5cb4ed17d131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Exam Date&quot;)</value>
      <webElementGuid>7265f77a-f6b7-4e3f-b9d6-98bf50bc0f31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Exam Date']</value>
      <webElementGuid>ff9e4dc5-bf58-41ba-b4fe-522f35edae9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/viewer-tab-form/div/div[2]/div/div/div[15]/div[6]/div/div/div/input</value>
      <webElementGuid>d6f22b13-3d8b-41b7-81a4-5b74782c2e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>63f7c2ba-0789-4213-a502-937d6a7d2bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Exam Date' and @id = 'Exam Date' and @placeholder = 'MM/dd/yyyy']</value>
      <webElementGuid>61f91bad-355d-422f-89b9-d5befd83c972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
